[package]
name = "cgen"
version = "0.1.0"
authors = ["chris.henderson <chris.henderson@alation.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.66"

[dev-dependencies]
lazy_static = "*"